data:extend({
        {
            type = "string-setting",
            name = "lossp-threshold-combination-rule",
            setting_type = "startup",
            default_value = "all",
			allowed_values = {"all", "average", "any"},
            order = "r",
		},
        {
            type = "bool-setting",
            name = "lossp-regulate-spawner-growth",
            setting_type = "startup",
            default_value = true,
            order = "r",
		},
        {
            type = "bool-setting",
            name = "lossp-regulate-worm-growth",
            setting_type = "startup",
            default_value = true,
            order = "r",
		},
        {
            type = "string-setting",
            name = "lossp-surface-list",
            setting_type = "startup",
            default_value = "nauvis,gleba",
            order = "r",
		},
        {
            type = "double-setting",
            name = "lossp-spitter-evo-threshold",
            setting_type = "startup",
            default_value = 0.3,
            minimum_value = 0,
            maximum_value = 1.0,
            order = "r",
		},
        {
            type = "double-setting",
            name = "lossp-worm-evo-threshold-factor",
            setting_type = "startup",
            default_value = 1.0,
            minimum_value = 0.1,
            maximum_value = 5.0,
            order = "r",
		},
})